### ISSUE TITLE
Python version problem

### ISSUE THREAD

**Issue by Abbadon89** [keton/etrv2mqtt#2]
At first im installing Adam's libertv (your library is using part of it so i assumed that is necessary)

> $ mkdir -p ~/venv/libetrv
> $ python3 -m venv ~/venv/libetrv
> $ source ~/venv/libetrv/bin/activate
> $ cd ~/venv/libetrv
> $ git clone https://github.com/AdamStrojek/libetrv.git
> $ cd cd libetrv/
> $ pip3 install -r requirements.txt

For now, everything is working fine. Now i start to install your lib.

> mkdir -p ~/venv/etrv2mqtt
> virtualenv ~/venv/etrv2mqtt
`created virtual environment CPython3.6.5.final.0-32 in 2148ms
  creator CPython3Posix(dest=/home/pi/venv/etrv2mqtt, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/pi/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
`

>  ~/venv/etrv2mqtt/bin/pip3 install 'git+https://github.com/keton/etrv2mqtt.git'

`
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/keton/etrv2mqtt.git
  Cloning https://github.com/keton/etrv2mqtt.git to /tmp/pip-req-build-as88nucd
  Running command git clone -q https://github.com/keton/etrv2mqtt.git /tmp/pip-req-build-as88nucd
ERROR: Package 'etrv2mqtt' requires a different Python: 3.6.5 not in '>=3.7'
`
According to error i recieve my python ver. is different than required. I tried to install with 3.7.X but without succes. For now its a bit too late to go deep with that but if you wish i can try it again tommorow.

**Comment by keton** [comment]
as the error message suggests intstall python 3.7. Also you don't need to install anything separately. Just do:
```
mkdir -p ~/venv/etrv2mqtt
virtualenv ~/venv/etrv2mqtt
~/venv/etrv2mqtt/bin/pip3 install 'git+https://github.com/keton/etrv2mqtt.git'
```

btw. Which distro are you using? 3.7 is two years old now and shipped by default with most linuxes based on Debian

**Comment by Abbadon89** [comment]
RPI 3 with raspbian stretch lite
I downloaded python 3.7 and compiled it according to this: 

>  wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
> tar xf Python-3.7.2.tar.xz
> cd Python-3.7.2
> ./configure
> make -j 4
> sudo make altinstall

Then i tried again without any success. I'm not in linux so much, its more like hobby for me so every problem i have try to solve with a lot of effort with assist of google, but when i fail with 20 open browser tabs its time to say 'i dont know'

**Comment by keton** [comment]
> raspbian stretch lite

That's from 2017, install buster from [RPI site](https://www.raspberrypi.org/downloads/raspbian/). Python is a core package in Raspbian so you most likely broke your install anyway. If you are a begginer stick to packages that you can get from `apt install`

**Comment by Abbadon89** [comment]
As you suggested i installed raspbian buster and everything is working fine. I have multiple eq3 thermostats and they report valve state 0%-100% its that possible with those valves?

**Comment by keton** [comment]
The only parameters reverse engineered so far are set point temperature, current temperature, name given in Danfoss app and battery level. We are limited by what thermostat firmware reports.
