### ISSUE TITLE
[Question] can I use etrv2mqtt to change schedules on the thermostat depending on geofencing settings? 

### ISSUE THREAD

**Issue by neuronflow** [keton/etrv2mqtt#6]
Hi,

I need schedules like:

USER A home:
7:45-10:30 -> 24°C
10:30-12:00 -> 21°C
12-19:30 -> 23°C
etc.

USER B home:
7:45-10:30 -> 22°C
10:30-12:00 -> 19°C
12-19:30 -> 21°C
etc.

USER A + C home:
7:45-10:30 -> 23°C
10:30-12:00 -> 20°C
12-19:30 -> 18°C
etc.

is it possible to achieve this using your library and HA? Thanks for your help?

**Comment by keton** [comment]
This sounds like something HA automation scripting could solve but I have no experience in this field.
